/*
 * generated by Xtext 2.14.0
 */
package ldas.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DucStandaloneSetup extends DucStandaloneSetupGenerated {

	def static void doSetup() {
		new DucStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
